name: Stark Web Audit
run-name: ${{ github.event.inputs.display-title }}

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Stark Token'
        required: true
      display-title:
        description: 'Display title'
        required: true

jobs:
  accessibility-audit:
    runs-on: ubuntu-latest

    name: Accessibility Audit
    steps:
      - name: Checkout code
        id: code-checkout
        uses: actions/checkout@v3

      - name: Audit
        id: stark
        uses: stark-contrast/accessibility-check-action@abhiraj/send-url-count-to-BE
        env: 
          STARK_REPORT_URL: 'https://abhiraj-stark.ngrok.io/api/cli-webhooks/scan-result/:scanId'
          STARK_DETAILS_URL: 'https://abhiraj-stark.ngrok.io/api/cli-webhooks/scan-details/:scanId'
          STARK_COMPLETION_URL: 'https://abhiraj-stark.ngrok.io/api/cli-webhooks/end-scan/:scanId'
        with:
            # Most of the following values are simply shell commands. You can use these to set up the container as needed for your app
            token: ${{ github.event.inputs.token }} # The action will use this to send an audit report back to Stark.
            wait_time: 100 # [Required, default 5000] Milliseconds to wait before your app can start serving
            urls: |-
                https://www.getstark.co/
                https://www.getstark.co/security/
                https://www.getstark.co/firefox/
                https://www.getstark.co/tos/
                https://www.getstark.co/adobe-xd/
                https://www.getstark.co/pricing/
                https://www.getstark.co/edge/
                https://www.getstark.co/cookies/
                https://www.getstark.co/blog/
                https://www.getstark.co/library/
                https://www.getstark.co/sketch/download/
